---
- name: Install Java 1.8 and some basic dependencies
  yum: name={{item}} state=present
  with_items:
   - unzip
   - java-1.8.0-openjdk
  
- name: Download WildFly from jboss.org
  get_url: url=http://download.jboss.org/wildfly/10.0.0.Final/wildfly-10.0.0.Final.zip dest=/opt/wildfly-10.0.0.Final.zip
  
- name: Extract archive
  command: chdir=/usr/share /usr/bin/unzip -q /opt/wildfly-10.0.0.Final.zip creates=/usr/share/jboss-as
#Rename the dir to avoid encoding the version in the init script
- name: Rename install directory
  command: chdir=/usr/share /bin/mv wildfly-10.0.0.Final jboss-as creates=/usr/share/jboss-as
  
- name: Add group "jboss"
  group: name=jboss
  
- name: Add user "jboss"
  user: name=jboss group=jboss home=/usr/share/jboss-as

- name: Change ownership of WildFly installation
  file: path=/usr/share/jboss-as/ owner=jboss group=jboss state=directory recurse=yes
  
- name: Copy the JBoss configuration file
  copy: src=/tmp/standalone.xml dest=/usr/share/jboss-as/standalone/configuration mode=0755
  
- name: Copy the application WAR
  copy: src=/tmp/petstore.war dest=/usr/share/jboss-as/standalone/deployments/petstore.war mode=0755
